exclude: '.git'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: docs
      - id: check-toml
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-isort]

  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python -m unittest
        language: python
        types: [python]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.0
    hooks:
    - id: commitizen
      stages: [commit-msg]
