[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38', 'py39']

[tool.coverage.run]
omit = [
    '*/.envs/*',
    '*/.virtualenvs/*',
    '*/__init__.py',
    'tests/*'
]

[tool.isort]
profile = 'black'
multi_line_output = 3

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.0"
