[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38', 'py39']

[tool.coverage.run]
omit = [
    '*/.virtualenvs/*',
    '*/__init__.py',
    'tests/*'
]

[tool.isort]
profile = 'black'
multi_line_output = 3
